from .wrap_resource_read_all import wrap__resource__read_all
from .wrap__resource__read_one import wrap__resource__read_one
from .wrap__resource__create_one import wrap__resource__create_one
from .wrap__resource__update_one import wrap__resource__update_one
from .wrap__resource__delete_one import wrap__resource__delete_one
from .wrap__resource__call_method import wrap__resource__call_method
