product_template_fields = {
    'default_list_domains': [],
    'list_fields': [
        'id',
        'sequence',
        ('categ_id', {'id', 'name'}),
        ('uom_id', {'id', 'name'}),
        ('company_id', {'id', 'name'}),
        'detailed_type',
        'type',
        'default_code',
        'name',
        'description',
        'list_price',
        'volume',
        'weight',
        'sale_ok',
        'purchase_ok',
        'active',
        'service_type',
        'x_stock_number',
        'x_case_count',
        'x_case_pack',
        'x_case_length',
        'x_case_width',
        'x_case_height',
        'x_case_cube',
        'x_case_weight',
        'x_upc',
        'show_availability',
        'available_threshold',
    ],
    'detail_fields': [
        'id',
        'sequence',
        ('categ_id', {'id', 'name'}),
        ('uom_id', {'id', 'name'}),
        ('company_id', {'id', 'name'}),
        'detailed_type',
        'type',
        'default_code',
        'name',
        'description',
        'list_price',
        'volume',
        'weight',
        'sale_ok',
        'purchase_ok',
        'active',
        'service_type',
        'x_stock_number',
        'x_case_count',
        'x_case_pack',
        'x_case_length',
        'x_case_width',
        'x_case_height',
        'x_case_cube',
        'x_case_weight',
        'x_upc',
        'show_availability',
        'available_threshold',
    ],
    'fields': [
        'id',
        'sequence',
        ('categ_id', {'id', 'name'}),
        ('uom_id', {'id', 'name'}),
        ('company_id', {'id', 'name'}),
        'detailed_type',
        'type',
        'default_code',
        'name',
        'description',
        'list_price',
        'volume',
        'weight',
        'sale_ok',
        'purchase_ok',
        'active',
        'service_type',
        'x_stock_number',
        'x_case_count',
        'x_case_pack',
        'x_case_length',
        'x_case_width',
        'x_case_height',
        'x_case_cube',
        'x_case_weight',
        'x_upc',
        'show_availability',
        'available_threshold',
    ],
    'default_create_fields': {}
}
