res_partner_fields = {
    'default_list_domains': [],
    'list_fields': [
         'id',
          ('company_id', {'id', 'name'}),
          'name',
          'title',
          ('parent_id', {'id', 'name'}),
          ('user_id', {'id', 'name'}),
          ('state_id', {'id', 'name'}),
          ('country_id', {'id', 'name'}),
          ('commercial_partner_id', {'id', 'name'}),
          'ref',
          'lang',
          'tz',
          'vat',
          'website',
          'function',
          'type',
          'zip',
          'city',
          'email',
          'phone',
          'mobile',
          'company_name',
          'date',
          'comment',
          'partner_latitude',
          'partner_longitude',
          'active',
          'employee',
          'is_company',
          ('team_id', {'id', 'name'}),
          'additional_info',
          'phone_sanitized',
          'supplier_rank',
          'customer_rank',
          ('website_id', {'id', 'name'}),
          'is_published',  
    ],
    'detail_fields': [
         'id',
          ('company_id', {'id', 'name'}),
          'name',
          'title',
          ('parent_id', {'id', 'name'}),
          ('user_id', {'id', 'name'}),
          ('state_id', {'id', 'name'}),
          ('country_id', {'id', 'name'}),
          ('commercial_partner_id', {'id', 'name'}),
          'ref',
          'lang',
          'tz',
          'vat',
          'website',
          'function',
          'type',
          'zip',
          'city',
          'email',
          'phone',
          'mobile',
          'company_name',
          'date',
          'comment',
          'partner_latitude',
          'partner_longitude',
          'active',
          'employee',
          'is_company',
          ('team_id', {'id', 'name'}),
          'additional_info',
          'phone_sanitized',
          'supplier_rank',
          'customer_rank',
          ('website_id', {'id', 'name'}),
          'is_published', 
    ],
    'fields': [
         'id',
          ('company_id', {'id', 'name'}),
          'name',
          'title',
          ('parent_id', {'id', 'name'}),
          ('user_id', {'id', 'name'}),
          ('state_id', {'id', 'name'}),
          ('country_id', {'id', 'name'}),
          ('commercial_partner_id', {'id', 'name'}),
          'ref',
          'lang',
          'tz',
          'vat',
          'website',
          'function',
          'type',
          'zip',
          'city',
          'email',
          'phone',
          'mobile',
          'company_name',
          'date',
          'comment',
          'partner_latitude',
          'partner_longitude',
          'active',
          'employee',
          'is_company',
          ('team_id', {'id', 'name'}),
          'additional_info',
          'phone_sanitized',
          'supplier_rank',
          'customer_rank',
          ('website_id', {'id', 'name'}),
          'is_published', 
    ],
    'default_create_fields': {}
}
